### ISSUE TITLE
Encoding issue in python 2.7 with py 1.4.32

### ISSUE THREAD

**Issue by tigarmo** [pytest-dev/py#106]
Hello,

After an update from version `1.4.31` to `1.4.32`, the following sample test started failing:

```python
# coding: utf-8
from __future__ import unicode_literals


def test_non_ascii_dir_path():
    from py.path import local
    from tempfile import gettempdir

    path_a = gettempdir()
    path_b = 'ação'

    directory = local(path_a).join(path_b)
    directory.ensure(dir=1)
```

Output:
```
py.test test_path.py
============================= test session starts =============================
platform win32 -- Python 2.7.12, pytest-2.9.3.dev0, py-1.4.32, pluggy-0.3.1
rootdir: D:\tmp\path, inifile:
collected 1 items

test_path.py F

================================== FAILURES ===================================
___________________________ test_non_ascii_dir_path ___________________________

    def test_non_ascii_dir_path():
        from py.path import local
        from tempfile import gettempdir

        path_a = gettempdir()
        path_b = 'a├º├úo'

        directory = local(path_a).join(path_b)
>       directory.ensure(dir=1)

test_path.py:13:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
D:\Miniconda\envs\steve-env\lib\site-packages\py\_path\local.py:524: in ensure
    return p._ensuredirs()
D:\Miniconda\envs\steve-env\lib\site-packages\py\_path\local.py:503: in _ensuredirs
    if parent == self:
D:\Miniconda\envs\steve-env\lib\site-packages\py\_path\local.py:166: in __eq__
    s2 = fspath(other)
D:\Miniconda\envs\steve-env\lib\site-packages\py\_path\common.py:28: in fspath
    return path_type.__fspath__(path)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = local(u'c:\\users\\tnobrega\\appdata\\local\\temp\\a\xe7\xe3o')

    def __fspath__(self):
>       return str(self)
E       UnicodeEncodeError: 'ascii' codec can't encode characters in position 38-39: ordinal not in range(128)
```

It looks like the relevant code was added in ef37a065f520d5122a (ping @aragilar, please have a look if you can), as an effort to backport `fspath` to pythons before 3.6. I am not sure how to fix this issue without breaking the py2 interface, and would like to start this discussion.

Thank you, and thanks for all your work.

**Comment by RonnyPfannschmidt** [comment]
looks like we missed a implementation bug, care to supply a patch replacing that `str(self)` with a `self.strpath` and adding a unittest for the behaviour?

**Comment by nicoddemus** [comment]
Thanks for the report @tigarmo!

~~The error is happening because `directory = local(path_a).join(path_b)` is dealing with `bytes` and `unicode` paths. I'm not sure what would be the proper fix though, perhaps others can chime in here.~~ @RonnyPfannschmidt beat me to it! :grin:

**Comment by tigarmo** [comment]
@RonnyPfannschmidt sure. I need a bit of time to get setup here (I assume pytest's [contribution guidelines](https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst) are valid here too) but I'll send a PR soon. Thanks!
