### ISSUE TITLE
DeprecationWarning: 'U' mode is deprecated

### ISSUE THREAD

**Issue by montefra** [pytest-dev/py#115]
From python 3.4 on, the 'U' mode of [``open``](https://docs.python.org/3/library/functions.html#open) has been deprecated.
According to [this answer](http://softwareengineering.stackexchange.com/a/298685/265868) the 'U' has been replaced by the ``newline`` argument, that when set to ``None``, the default, uses universal new line.
I have identified only three ``rU`` modes. Two in the [``readline``](https://github.com/pytest-dev/py/blob/master/py/_path/common.py#L170) function and one regarding [svn](https://github.com/pytest-dev/py/blob/master/py/_path/svnurl.py#L98).

- [x] If it's fine with you, for the first two cases I'll do a PR where I set the mode to ``rU`` for python 2 and ``r`` otherwise.
- [ ] I don't think that I need to touch the svn case, as the mode is never used

**Comment by RonnyPfannschmidt** [comment]
Since Python 3.3 is in the support Matrix, does that work the same?

**Comment by montefra** [comment]
It seems so: https://docs.python.org/3.3/library/functions.html#open.

The ``newline`` argument is present and

> 'U'	universal newlines mode (for backwards compatibility; should not be used in new code)

**Comment by RonnyPfannschmidt** [comment]
The PR you propose is def an enhancement

we will have to follow up with open and read eventially tho

**Comment by montefra** [comment]
I can start with readlines and then work my way through.
I discovered the deprecation through pytest-warnings and I think that I can temporarily enable it to check. I'll start the PR early next week

**Comment by RonnyPfannschmidt** [comment]
closed by #116
