### ISSUE TITLE
Use the correct bugtrack_url

### ISSUE THREAD

**Issue by jayfk** [pytest-dev/py#117]
The `bugtrack_url` field on PyPi is still pointing to the old issue tracker at https://bitbucket.org/hpk42/py/issues

From what it looks like this field can be set on PyPi only, it's not being picked up from `setup.py`.

Link to the latest release on PyPi: https://pypi.python.org/pypi/py/1.4.33

**Comment by The-Compiler** [comment]
I do have owner permissions for py on PyPI, but I can't find a place to edit this. Looks like it's not editable anymore... 😟 https://github.com/pypa/pypi-legacy/issues/581

**Comment by jayfk** [comment]
Argh, okay.

**Comment by The-Compiler** [comment]
The PyPI bug was fixed, so I updated it now!
