### ISSUE TITLE
make_numbered_dir breaks on case-sensitive filesystems

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/py#119]
in case of a case-miss-matched filesystem make_numbered_dir counts incorrectly

the solution would be to case-normalize the counting elements in order to find a correct maxnum
however we could also consider increment on errors

this issue causes pytest-dev/pytest#2323

**Comment by dnozay** [comment]
> make_numbered_dir breaks on case-sensitive filesystems #119

Did you mean case-insensitive filesystem instead?

See https://github.com/pytest-dev/py/pull/121

**Comment by dnozay** [comment]
See also https://github.com/pytest-dev/pytest/issues/708

**Comment by dnozay** [comment]
@RonnyPfannschmidt could you please help me close this 2015 bug? :)

**Comment by RonnyPfannschmidt** [comment]
fixed by a6392dd - thanks for the patch and preserving to get it noticed
