### ISSUE TITLE
Pylint complains about `from py.path import local`

### ISSUE THREAD

**Issue by vlcinsky** [pytest-dev/py#120]
My code often uses an idiom `from py.path import local`:
```python
from py.path import local

def test_something():
    fname = local("tests/data.json")
    assert fname.exists()
```
All works well apart from pylint complaining:
```
E:  1, 0: No name 'path' in module 'py' (no-name-in-module)
E:  1, 0: Unable to import 'py.path' (import-error)
```

Is there any way to make pylint happier about that import?

**Comment by RonnyPfannschmidt** [comment]
this is pylint false positives, please report an issue to pylint

**Comment by vlcinsky** [comment]
Good.
Seems like it is already filed: PyCQA/pylint#640
