### ISSUE TITLE
test_svnwc.py is failing on Windows

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/py#161]
Output of the failures from AppVeyor in build [1.0.8](https://ci.appveyor.com/project/pytestbot/py/build/1.0.8): https://gist.github.com/nicoddemus/85b100282dabab1d1b7acd98c8795059

Skipping those tests for now until someone interested wants to pick this up.

**Comment by RonnyPfannschmidt** [comment]
shouldnt we use xfail(run=False) ?

**Comment by nicoddemus** [comment]
Of course, thanks for the pointer. Updated the PR.
