### ISSUE TITLE
py 1.5 breaks py.log: "No module named syslog"

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/py#170]
Unfortunately the changes introduced in 7f46178c972155f49ec5376b273f63492d9c7d2e break on Windows, and my PR in #157 did not take the proper approach of detecting and fixing the problem. 😓

**Comment by nicoddemus** [comment]
Fixed by #171

**Comment by mrbean-bremen** [comment]
@nicoddemus - thanks for the fast fix!
There is one problem left though for [existing Python 3.3 builds](https://ci.appveyor.com/project/mrbean-bremen/pyfakefs/build/1.0.24) - as 1.5.0 is the last version supporting Python 3.3, this version is now installed with the latest `py.test` under Python 3.3 - that breaks pytest under Windows. It would be nice to have another version of `py` with Python 3.3 enabled in `setup.py`, so it can be installed from pypi for this version (alternatively, `py.test` requirements could be adapted to only accept `py` < 1.5.0 for Python 3.3). 
What do you think?

**Comment by nicoddemus** [comment]
Hi @mrbean-bremen, thanks for writing.

To solve this we were considering removing `py-1.5.0` from PyPI given that it has irrevocably wrong meta-data. I guess this is the solution, so I will do that shortly. 

> alternatively, py.test requirements could be adapted to only accept py < 1.5.0 for Python 3.3

Indeed that's what we did in `pytest-3.2.4`, but there are issues with `pip` dependency resolver (see 
 pytest-dev/pytest#2926); if not for that I think we would not have had all this problems.

**Comment by nicoddemus** [comment]
And it has been removed. @mrbean-bremen this should fix your builds now.

Hopefully this is the end of that.

**Comment by mrbean-bremen** [comment]
@nicoddemus - thanks a lot, works like a charm now!
