### ISSUE TITLE
Use shutil.get_terminal_size() in Python 3

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/py#174]
Let's use [`shutil.get_terminal_size`](https://docs.python.org/3/library/shutil.html#shutil.get_terminal_size) if available. This produces the correct size on Windows, and seems pretty fast:

```
$ python -m timeit -s "import shutil" "shutil.get_terminal_size()"
100000 loops, best of 3: 14.6 usec per loop
```

**Comment by Victorious3** [comment]
Yes, please, this is the second thing that's bugging me! I can make a PR for this if required.

**Comment by nicoddemus** [comment]
> I can make a PR for this if required.

A PR would be welcome, thanks! 😁
