### ISSUE TITLE
Error during import py :      'module' object has no attribute 'builtin'

### ISSUE THREAD

**Issue by arita37** [pytest-dev/py#176]
When doing   import py

I have this message : 

```

python2.7/site-packages/_pytest/_code/code.py in <module>()
      7 builtin_repr = repr
      8
----> 9 reprlib = py.builtin._tryimport('repr', 'reprlib')
     10
     11 if sys.version_info[0] >= 3:

AttributeError: 'module' object has no attribute 'builtin'

```

**Comment by RonnyPfannschmidt** [comment]
do you by chance have a local file called py.py or a own python package called py?

else what versions of those packages have you installed and what does your folder tree look like?

**Comment by arita37** [comment]
problem solved :

Install package pytest instead of py

py is deprecated !!!


On Nov 26, 2017, at 17:31, Ronny Pfannschmidt <notifications@github.com> wrote:

do you by chance have a local file called py.py or a own python package called py?

else what versions of those packages have you installed and what does your folder tree look like?

―

**Comment by RonnyPfannschmidt** [comment]
thanks for following up
