### ISSUE TITLE
Maintenance mode, is there an alternative?

### ISSUE THREAD

**Issue by WoLpH** [pytest-dev/py#178]
Hi guys,

I just noticed that this library is not recommended for new projects anymore which is too bad since I quite like the features provided by `py.path`. So I'm wondering, what's the reasoning behind this? Is there an alternative library to use?

Especially in small shell scripts it can be far more convenient (and clearer) to do:
```python
path.join('something').write('some text', ensure=True)
```
Than writing:
```python
if not os.path.isdir(path):
    os.makedirs(path)

with open(os.path.join(path, 'something'), 'w') as fh:
    fh.write('some text')
```

**Comment by RonnyPfannschmidt** [comment]
for path operations i generally suggest pathlib/pathlib2

**Comment by WoLpH** [comment]
I didn't consider pathlib because I wasn't aware there were backports available. That helps a lot :)

Should that recommendation (and perhaps others) be added to the readme as well? I can't be the only one that has this question

**Comment by jsmedmar** [comment]
py.path is very nice :), pathlib/pathlib2 recommendation would be great in readme
