### ISSUE TITLE
PEP 561 uses "py" namespace

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/py#185]
So I just read [PEP 561](https://www.python.org/dev/peps/pep-0561/) and noticed it uses package data for the `py.typed` package (plus apparently such a file in the package?) for type stubs.

Is that going to be an issue? Would it make sense to try and convince the authors to not use `py.typed` as name for that marker?

**Comment by RonnyPfannschmidt** [comment]
based on a initial skim, this is a in package package data filename, so i don't see any issues

**Comment by asottile** [comment]
This is just a data file and not actually a namespace.

For example, if I wanted to indicate that `mymod` is typed I'd have a structure like:

```
mymod/
├── __init__.py
├── foo.py
└── py.typed
```

And then I'd include the `py.typed` file as part of the `package_data` in setup.py
