### ISSUE TITLE
Document `strpath` attribute of `LocalPath` object

### ISSUE THREAD

**Issue by asottile** [pytest-dev/py#187]
lots of code uses this attribute, but it is not [documented](http://py.readthedocs.io/en/latest/path.html#py._path.local.LocalPath)

how do I convince the sphinx docs to include this 😆 

(note that it _is_ included for `svnwc`)

Originally noticed [here](https://github.com/pre-commit/pre-commit-hooks/pull/301#discussion_r198250149)

**Comment by RonnyPfannschmidt** [comment]
it shouldnt be used to begin with

**Comment by asottile** [comment]
pytest uses it: https://github.com/pytest-dev/pytest/search?q=strpath&unscoped_q=strpath

It has one benefit over `str(localpathobj)` in that it preserves `bytes`  / `text`:

```python
>>> # python 2
>>> local.LocalPath(u'bar').strpath
u'/private/tmp/py/bar'
>>> # python 3
>>> LocalPath(b'foo').strpath
b'/private/tmp/py/foo'
```

**Comment by RonnyPfannschmidt** [comment]
@asottile pytest will completely remove all internal py.path.local usage in the next few months

**Comment by RonnyPfannschmidt** [comment]
once thats done we will deprecate all local path based apis ^^

**Comment by RonnyPfannschmidt** [comment]
@asottile on a extra note - py.path.local is unreasonably unaware of unicode vs bytest, its at best irresponsible to rely on it for that distinction

**Comment by asottile** [comment]
Sure, but it's going to be incredibly difficult to remove due to `tmpdir` publically, it's a public name, and quite a lot of code on github uses it

**Comment by RonnyPfannschmidt** [comment]
oh, we won't remove it, just deprecate it ^^

**Comment by asottile** [comment]
In the meantime (especially since it's used) can we improve this from a public undocumented attribute to a documented one?

**Comment by RonnyPfannschmidt** [comment]
as long as the broken fundamentals of it are documented as well

**Comment by asottile** [comment]
seems even `str(...)` isn't documented 🙃

**Comment by RonnyPfannschmidt** [comment]
im not exactly surprised, im going to be really happy once its gone ^^

**Comment by wimglenn** [comment]
Hmm, should I have used this .strpath attribute in https://github.com/pytest-dev/pytest/pull/3848 ?  I wasn't aware of it.
