### ISSUE TITLE
Don't create link in make_numbered_dir

### ISSUE THREAD

**Issue by anxuae** [pytest-dev/py#194]
It it possible to make optional the link creation et the end of the method `make_numbered_dir`?

Using the option `--basetemp` with `pytest` has the consequence to create a link to each temporary directory, thus double the quantity of folders and let the temp directory less readable.

**Comment by RonnyPfannschmidt** [comment]
i plan to port pytests normcase handling to pathlib2 in the near future
as for py - at least i am no longer working on maintaining it

**Comment by RonnyPfannschmidt** [comment]
closing as wontfix - pytest no longer uses py.path.local for numbered dirs
