### ISSUE TITLE
`pyimport` fails for intentionally mismatching source/bytecode suffixes

### ISSUE THREAD

**Issue by brandonwillard** [pytest-dev/py#195]
A check occuring [here](https://github.com/pytest-dev/py/blob/master/py/_path/local.py#L674) assumes that a module loaded from bytecode with a `__file__` attribute ending in `pyc` must have a source file with suffix `.py`.  This is not the case for the code I'm working on (https://github.com/hylang/hy), which has source files with intentionally different suffixes that compile to `.pyc`, and ultimately causes `pyimport` to fail.

**Comment by RonnyPfannschmidt** [comment]
Pytest no longer uses this code path
