### ISSUE TITLE
Building with pytest4 does not work at all

### ISSUE THREAD

**Issue by scarabeusiv** [pytest-dev/py#209]
In distributions we try to have tests enabled to ensure updating components does not break the applications shipped, esp. with python which is evaluated on runtime this is crucial. But we can't provide multiple versions of pytest and as such we can't do the same process like in here where you pinned old version of pytest and are happy.

Full log [py.txt](https://github.com/pytest-dev/py/files/2869015/py.txt)

This is tied to issue #162 which I for now solved by deleting the offending test file...

**Comment by blueyed** [comment]
Yeah, it's in bad shape.

For now you could try building with tox instead - after all pytest is only used to run the tests, but pytest itself works with the latest py.

@nicoddemus @RonnyPfannschmidt 
As for fixing the tests:
What minimum pytest version do we want to use?
I think for the removal of `getfuncargvalue` alone it would make sense to only test with pytest 3.0+.

**Comment by blueyed** [comment]
I assume the usage of `pytest_funcarg__*` needs to be replaced, and the FAQ being removed?
https://github.com/pytest-dev/py/blob/a7847eda06046e466d8c63a7a2885ed9f2aba662/doc/faq.txt#L101-L113

**Comment by nicoddemus** [comment]
> I think for the removal of `getfuncargvalue` alone it would make sense to only test with pytest 3.0+.

Agreed! 👍
