### ISSUE TITLE
Pytest collects the same tests multiple times after upgrading py to the newest version (1.8.1 -> 1.8.2)

### ISSUE THREAD

**Issue by spryg** [pytest-dev/py#246]
It is related to the changes in local.py

1.8.1: 
`    def __hash__(self):
        return hash(self.strpath))`
1.8.2: 
`    def __hash__(self):
        s = self.strpath
        if iswin32:
            s = s.lower()
        return hash(s)`

**Comment by bluetech** [comment]
Can you provide a minimal reproduction?
