### ISSUE TITLE
py.__spec__ is not set

### ISSUE THREAD

**Issue by undera** [pytest-dev/py#253]
Something inside lib does replace original module with another object, missing `__spec__` attribute. Because of this, `importlib` raises exception when trying to find spec of `py`. 

I have simplified my usecase to the following minimal code:

```python
from importlib import util as importlib_util

import py

importlib_util.find_spec(py.__name__)
```

It raises `ValueError`.

**Comment by bluetech** [comment]
py does some funky stuff with its top-level package (see [apipkg](https://github.com/pytest-dev/apipkg) for more details). I personally am not a fan but it is/was considered a feature, and is unlikely to change at this point...

**Comment by RonnyPfannschmidt** [comment]
Should we consider this for apipkg and the devendoring

**Comment by undera** [comment]
Why not just fix it by adding `__spec__` copying, the same way other properties are copied?

**Comment by RonnyPfannschmidt** [comment]
It has to be fixed in apipkg and re-vendored or devendored in pylib
