### ISSUE TITLE
How do I turn off escaping?

### ISSUE THREAD

**Issue by headtr1ck** [pytest-dev/py#274]
I want to create a HTML script tag which requires quotes.
If I simply use
```
from py.xml import html
html.script( "MathJax = { tex: { inlineMath: [['$', '$'], ['\\(', '\\)']] } };")
```
the quotes `'` get escaped and I end up with:
`MathJax = { tex: { inlineMath: [[&apos;$&apos;, &apos;$&apos;], [&apos;\(&apos;, &apos;\)&apos;]] } };`
which ofc does not work as javascript.
Is there a way to disable escaping? I could not find anything in the docu.

**Comment by RonnyPfannschmidt** [comment]
wrap into `py.xml.raw`

but seriously, stop using this lib, its unmaintained and we work on dropping its usage from pytest

**Comment by headtr1ck** [comment]
Thanks.
And I'll get rid of this packet, was just copying what pytest-html was doing :)
