### ISSUE TITLE
pylib (latest) documentation missing

### ISSUE THREAD

**Issue by sashkab** [pytest-dev/py#87]
I tried to consult pylib documentation at http://pylib.readthedocs.io/en/latest/ and it showing placeholder page.

By default, when going to http://pylib.readthedocs.io, it will get redirected to the latest.

Stable version is available at http://pylib.readthedocs.io/en/stable/, so you might want to setup to redirect to stable by default.

**Comment by RonnyPfannschmidt** [comment]
the build is indeed failing
i'll fix the configruation now

**Comment by RonnyPfannschmidt** [comment]
http://py.readthedocs.io/en/latest/ is fixed

we forgot to check to "install project" checkbox when changing settings
thanks for pointing
