### ISSUE TITLE
Docs seem to be broken

### ISSUE THREAD

**Issue by hackebrot** [pytest-dev/py#91]
Hey @RonnyPfannschmidt,

I think the docs are broken since the move to GitHub.

See http://pylib.readthedocs.io/en/latest/

Raphael

**Comment by RonnyPfannschmidt** [comment]
@hackebrot oh yikes, we have 2 projects on there ? the other url is http://py.readthedocs.io

@hpk42 i think i don't have access to that one, can you add @flub and me ? and/or remove it/redirect it

**Comment by flub** [comment]
oh, the PyPI page actually refers to the pylib.rtfd.io version...
(I also don't have currently access to it)

**Comment by aroberge** [comment]
The readme file on this very site refers to http://pylib.readthedocs.io/ instead of http://py.readthedocs.io/
