### ISSUE TITLE
Update HTML tags

### ISSUE THREAD

**Issue by davehunt** [pytest-dev/py#94]
The [HTML tag list](https://github.com/pytest-dev/py/blob/3afedbdd6d3aa3f261498bcf9d239726023e0f15/py/_xmlgen.py#L76-L87) is out of date. It would be great to update it with the latest accepted values (such as video, source, etc) as defined [here](http://w3c.github.io/html-reference/elements.html).

**Comment by denisra** [comment]
@davehunt I can probably help with this one. 
One question though, should we also remove the tags that are not listed in the w3c website any more?
Most likely they have been deprecated, as it is the case for the acronym tag, for example.

**Comment by RonnyPfannschmidt** [comment]
@denisra they have to stay for backward compatibility for now

**Comment by denisra** [comment]
@RonnyPfannschmidt that makes sense. Thanks for the confirmation. Let me just update the tag list with the new ones then.

**Comment by blueyed** [comment]
Should be closed since #95 has been merged.

I cannot close it myself?!

**Comment by RonnyPfannschmidt** [comment]
@blueyed cannot be closed until release

**Comment by davehunt** [comment]
@RonnyPfannschmidt could you perhaps assign this to @denisra or yourself so that it is not advertised an open and unassigned?

**Comment by RonnyPfannschmidt** [comment]
@davehunt release done, happy adapting
