### ISSUE TITLE
py.path.local('/').join('tox.ini') produces '//tox.ini', causing pytest to hang on cygwin.

### ISSUE THREAD

**Issue by account-login** [pytest-dev/py#97]
The double slash path is causing problems, see https://github.com/pytest-dev/pytest/issues/2135 for details.

This issue can be fixed by changing `strpath = strpath + sep + arg` to `strpath = strpath.rstrip(sep) + sep + arg` in `py.path.local.join()`

**Comment by RonnyPfannschmidt** [comment]
fixed by #127
